title: JSON Structure
logo: /media/logo.svg
url: https://json-structure.org
description:  JSON Structure is a data structure definition language that enforces strict typing, modularity, and determinism.
show_downloads: false
author:
  name: "Clemens Vasters"
  email: "clemensv@microsoft.com"
github:
  repository_url: https://github.com/json-structure
  repository_nwo: json-structure
  owner_name: clemensv
  owner_url: https://github.com/clemensv

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Default front matter for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post